fix: improve density

diff --git a/_modules/aws/kubernetes-region-cluster/module/manifests/helm-manifests/eks-aws-csi-topolvm.yaml b/_modules/aws/kubernetes-region-cluster/module/manifests/helm-manifests/eks-aws-csi-topolvm.yaml
--- a/_modules/aws/kubernetes-region-cluster/module/manifests/helm-manifests/eks-aws-csi-topolvm.yaml
+++ b/_modules/aws/kubernetes-region-cluster/module/manifests/helm-manifests/eks-aws-csi-topolvm.yaml
@@ -66,26 +66,12 @@ spec:
                     operator: In
                     values:
                       - linux
-          preferredDuringSchedulingIgnoredDuringExecution:
-            - weight: 100
-              preference:
-                matchExpressions:
-                  - key: role
-                    operator: NotIn
-                    values:
-                      - system
-            - weight: 100
-              preference:
-                matchExpressions:
-                  - key: kubernetes.io/arch
-                    operator: In
-                    values:
-                      - arm64
 
       topologySpreadConstraints:
-        - maxSkew: 1
-          topologyKey: topology.kubernetes.io/zone
+        - maxSkew: 2
+          minDomains: 2
           whenUnsatisfiable: DoNotSchedule
+          topologyKey: topology.kubernetes.io/zone
           labelSelector:
             matchLabels:
               app.kubernetes.io/name: topolvm
@@ -120,118 +106,118 @@ spec:
             - /bin/bash
             - -c
             - |
-                #!/bin/bash
-                declare -A log_levels=( [FATAL]=0 [ERROR]=3 [WARNING]=4 [INFO]=6 [DEBUG]=7)
-                if ! command -v date &> /dev/null
-                then
-                    echo "date could not be found"
-                    exit
-                fi
-                if ! command -v jq &> /dev/null
-                then
-                    echo "jq could not be found"
-                    exit
-                fi
-                json_logger() {
-                  log_level=$$1
-                  message=$$2
-                  level=$${log_levels[$$log_level]}
-                  timestamp=$$(date -I'ns')
-                  jq --raw-input --compact-output \
-                    '{
-                      "level": "'$$log_level'",
-                      "timestamp": "'$$timestamp'",
-                      "message": .
-                    }'
-                }
+              #!/bin/bash
+              declare -A log_levels=( [FATAL]=0 [ERROR]=3 [WARNING]=4 [INFO]=6 [DEBUG]=7)
+              if ! command -v date &> /dev/null
+              then
+                  echo "date could not be found"
+                  exit
+              fi
+              if ! command -v jq &> /dev/null
+              then
+                  echo "jq could not be found"
+                  exit
+              fi
+              json_logger() {
+                log_level=$$1
+                message=$$2
+                level=$${log_levels[$$log_level]}
+                timestamp=$$(date -I'ns')
+                jq --raw-input --compact-output \
+                  '{
+                    "level": "'$$log_level'",
+                    "timestamp": "'$$timestamp'",
+                    "message": .
+                  }'
+              }
 
-                trap 'catch $$? $$LINENO' ERR
+              trap 'catch $$? $$LINENO' ERR
 
-                catch() {
-                  echo "Error $$1 occurred on $$2" | json_logger "FATAL"
-                  trap '' INT TERM
-                  sleep infinity & pid=$$!
-
-                  while wait $$pid; test $$? -ge 128
-                  do echo 'exiting' | json_logger "INFO"
-                  done
-                  exit 1
-                }
-
-
-
-                if ! command -v nvme &> /dev/null
-                then
-                    echo "nvme could not be found" | json_logger "FATAL"
-                    exit
-                fi
-                if ! command -v grep &> /dev/null
-                then
-                    echo "grep could not be found" | json_logger "FATAL"
-                    exit
-                fi
-                if ! command -v cut &> /dev/null
-                then
-                    echo "cut could not be found" | json_logger "FATAL"
-                    exit
-                fi
-                if ! command -v vgscan &> /dev/null
-                then
-                    echo "vgscan could not be found" | json_logger "FATAL"
-                    exit
-                fi
-                if ! command -v vgcreate &> /dev/null
-                then
-                    echo "vgcreate could not be found" | json_logger "FATAL"
-                    exit
-                fi
-                if ! command -v pvcreate &> /dev/null
-                then
-                    echo "pvcreate could not be found" | json_logger "FATAL"
-                    exit
-                fi
-                PLATFORM="$${1:-aws}"
-                echo Platform is $$PLATFORM | json_logger "INFO"
-                nvme list --output-format=json | tr '^ *' ' ' |  tr '\n' ' ' | json_logger "INFO"
-                OUTPUT=$$(vgdisplay || true 2> /dev/null | grep $${VG_NAME:-instancestore})
-                if [ $$PLATFORM == aws ]; then
-                  condition="Instance"
-                elif [ $$PLATFORM == azure ]; then
-                  condition="Microsoft NVMe Direct Disk"
-                elif [ $$PLATFORM == gcp ]; then
-                  condition="nvme_card"
-                else
-                  echo PLATFORM IS UNKNOWN | json_logger "FATAL"
-                  exit 1 #We should not be here
-                fi
-
-                if [ -z "$$OUTPUT" ]
-                then
-                    echo "VG does not exist this is normal if this is a new node" | json_logger "INFO"
-                    declare -r disks=($$(nvme list | grep "$$condition" | cut -f 1 -d ' '))
-                    if (( $${#disks[@]} )); then
-                        for i in "$${disks[@]}"
-                        do
-                            echo "Creating PV $$i" | json_logger "INFO"
-                            pvcreate -ff -y $$i
-                        done
-
-
-                        echo "Creating VG=$${VG_NAME:-instancestore} $$(printf '%s ' $${disks[@]})" | json_logger "INFO"
-                        vgcreate $${VG_NAME:-instancestore} $$(printf '%s ' $${disks[@]}) | json_logger "INFO"
-                    fi
-                else
-                    echo "VG exists that is unexpected if this is a new node" | json_logger "INFO"
-                fi
-
-
-
+              catch() {
+                echo "Error $$1 occurred on $$2" | json_logger "FATAL"
                 trap '' INT TERM
-                # sleep infinity & pid=$$!
+                sleep infinity & pid=$$!
 
                 while wait $$pid; test $$? -ge 128
                 do echo 'exiting' | json_logger "INFO"
                 done
+                exit 1
+              }
+
+
+
+              if ! command -v nvme &> /dev/null
+              then
+                  echo "nvme could not be found" | json_logger "FATAL"
+                  exit
+              fi
+              if ! command -v grep &> /dev/null
+              then
+                  echo "grep could not be found" | json_logger "FATAL"
+                  exit
+              fi
+              if ! command -v cut &> /dev/null
+              then
+                  echo "cut could not be found" | json_logger "FATAL"
+                  exit
+              fi
+              if ! command -v vgscan &> /dev/null
+              then
+                  echo "vgscan could not be found" | json_logger "FATAL"
+                  exit
+              fi
+              if ! command -v vgcreate &> /dev/null
+              then
+                  echo "vgcreate could not be found" | json_logger "FATAL"
+                  exit
+              fi
+              if ! command -v pvcreate &> /dev/null
+              then
+                  echo "pvcreate could not be found" | json_logger "FATAL"
+                  exit
+              fi
+              PLATFORM="$${1:-aws}"
+              echo Platform is $$PLATFORM | json_logger "INFO"
+              nvme list --output-format=json | tr '^ *' ' ' |  tr '\n' ' ' | json_logger "INFO"
+              OUTPUT=$$(vgdisplay || true 2> /dev/null | grep $${VG_NAME:-instancestore})
+              if [ $$PLATFORM == aws ]; then
+                condition="Instance"
+              elif [ $$PLATFORM == azure ]; then
+                condition="Microsoft NVMe Direct Disk"
+              elif [ $$PLATFORM == gcp ]; then
+                condition="nvme_card"
+              else
+                echo PLATFORM IS UNKNOWN | json_logger "FATAL"
+                exit 1 #We should not be here
+              fi
+
+              if [ -z "$$OUTPUT" ]
+              then
+                  echo "VG does not exist this is normal if this is a new node" | json_logger "INFO"
+                  declare -r disks=($$(nvme list | grep "$$condition" | cut -f 1 -d ' '))
+                  if (( $${#disks[@]} )); then
+                      for i in "$${disks[@]}"
+                      do
+                          echo "Creating PV $$i" | json_logger "INFO"
+                          pvcreate -ff -y $$i
+                      done
+
+
+                      echo "Creating VG=$${VG_NAME:-instancestore} $$(printf '%s ' $${disks[@]})" | json_logger "INFO"
+                      vgcreate $${VG_NAME:-instancestore} $$(printf '%s ' $${disks[@]}) | json_logger "INFO"
+                  fi
+              else
+                  echo "VG exists that is unexpected if this is a new node" | json_logger "INFO"
+              fi
+
+
+
+              trap '' INT TERM
+              # sleep infinity & pid=$$!
+
+              while wait $$pid; test $$? -ge 128
+              do echo 'exiting' | json_logger "INFO"
+              done
 
           imagePullPolicy: IfNotPresent
           env:
@@ -284,26 +270,11 @@ spec:
                     operator: In
                     values:
                       - linux
-          preferredDuringSchedulingIgnoredDuringExecution:
-            - weight: 100
-              preference:
-                matchExpressions:
-                  - key: role
-                    operator: NotIn
-                    values:
-                      - system
-            - weight: 100
-              preference:
-                matchExpressions:
-                  - key: kubernetes.io/arch
-                    operator: In
-                    values:
-                      - arm64
-
       topologySpreadConstraints:
-        - maxSkew: 1
-          topologyKey: topology.kubernetes.io/zone
+        - maxSkew: 2
+          minDomains: 2
           whenUnsatisfiable: DoNotSchedule
+          topologyKey: topology.kubernetes.io/zone
           labelSelector:
             matchLabels:
               app.kubernetes.io/name: topolvm
